=== jessaskey/mhedit/GameEditor.Core/Xsd/GameProfile.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema id="NewDataSet" xmlns="" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:msdata="urn:schemas-microsoft-com:xml-msdata">
  <xs:element name="StorageDefinition">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Short" type="xs:string" minOccurs="0" msdata:Ordinal="0" />
        <xs:element name="PageRef" nillable="true" minOccurs="0" maxOccurs="unbounded">
          <xs:complexType>
            <xs:simpleContent msdata:ColumnName="PageRef_Text" msdata:Ordinal="2">
              <xs:extension base="xs:string">
                <xs:attribute name="Path" type="xs:string" />
                <xs:attribute name="Name" type="xs:string" />
              </xs:extension>
            </xs:simpleContent>
          </xs:complexType>
        </xs:element>
        <xs:element ref="Array" minOccurs="0" maxOccurs="unbounded" />
      </xs:sequence>
      <xs:attribute name="Id" type="xs:string" />
    </xs:complexType>
  </xs:element>
  <xs:element name="StorageDefinitionRef">
    <xs:complexType>
      <xs:attribute name="Id" type="xs:string" />
      <xs:attribute name="Order" type="xs:string" />
      <xs:attribute name="Delimiter" type="xs:string" />
    </xs:complexType>
  </xs:element>
  <xs:element name="Array">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="StorageDefinitionRef" minOccurs="0" maxOccurs="unbounded" />
      </xs:sequence>
      <xs:attribute name="StorageClass" type="xs:string" />
      <xs:attribute name="DataType" type="xs:string" />
      <xs:attribute name="Id" type="xs:string" />
      <xs:attribute name="Size" type="xs:string" />
    </xs:complexType>
  </xs:element>
  <xs:element name="FeatureGroupRef">
    <xs:complexType>
      <xs:attribute name="Id" type="xs:string" />
    </xs:complexType>
  </xs:element>
  <xs:element name="FeatureRef">
    <xs:complexType>
      <xs:attribute name="Id" type="xs:string" />
      <xs:attribute name="Maximum" type="xs:string" />
      <xs:attribute name="Required" type="xs:string" />
    </xs:complexType>
  </xs:element>
  <xs:element name="GameProfile">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="GameInfo" minOccurs="0" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="Name" type="xs:string" minOccurs="0" />
              <xs:element name="Version" type="xs:string" minOccurs="0" />
              <xs:element name="Manufacturer" type="xs:string" minOccurs="0" />
              <xs:element name="ReleaseDate" type="xs:string" minOccurs="0" />
              <xs:element name="Comment" type="xs:string" minOccurs="0" />
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="MemoryMap" minOccurs="0" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="ROM" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="Memory" minOccurs="0" maxOccurs="unbounded">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="Bank" minOccurs="0" maxOccurs="unbounded">
                            <xs:complexType>
                              <xs:sequence>
                                <xs:element name="EEPROM" minOccurs="0" maxOccurs="unbounded">
                                  <xs:complexType>
                                    <xs:attribute name="Id" type="xs:string" />
                                    <xs:attribute name="Name" type="xs:string" />
                                    <xs:attribute name="Size" type="xs:string" />
                                    <xs:attribute name="Width" type="xs:string" />
                                  </xs:complexType>
                                </xs:element>
                              </xs:sequence>
                              <xs:attribute name="Id" type="xs:string" />
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="Pages" minOccurs="0" maxOccurs="unbounded">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="Page" minOccurs="0" maxOccurs="unbounded">
                            <xs:complexType>
                              <xs:sequence>
                                <xs:element name="BankRef" minOccurs="0" maxOccurs="unbounded">
                                  <xs:complexType>
                                    <xs:attribute name="Id" type="xs:string" />
                                  </xs:complexType>
                                </xs:element>
                              </xs:sequence>
                              <xs:attribute name="Id" type="xs:string" />
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                  <xs:attribute name="Id" type="xs:string" />
                  <xs:attribute name="Address" type="xs:string" />
                  <xs:attribute name="Size" type="xs:string" />
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute name="Id" type="xs:string" />
            <xs:attribute name="AddressWidth" type="xs:string" />
            <xs:attribute name="AddressBase" type="xs:string" />
            <xs:attribute name="BusWidth" type="xs:string" />
          </xs:complexType>
        </xs:element>
        <xs:element name="ProgramMemory" minOccurs="0" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="TextSegment" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="Data" minOccurs="0" maxOccurs="unbounded">
                      <xs:complexType>
                        <xs:attribute name="Path" type="xs:string" />
                        <xs:attribute name="Name" type="xs:string" />
                        <xs:attribute name="Reserved" type="xs:string" />
                        <xs:attribute name="Start" type="xs:string" />
                        <xs:attribute name="Length" type="xs:string" />
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="Checksum" minOccurs="0" maxOccurs="unbounded">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="EEPROMRef" minOccurs="0" maxOccurs="unbounded">
                            <xs:complexType>
                              <xs:attribute name="Path" type="xs:string" />
                              <xs:attribute name="Name" type="xs:string" />
                              <xs:attribute name="Start" type="xs:string" />
                              <xs:attribute name="End" type="xs:string" />
                            </xs:complexType>
                          </xs:element>
                          <xs:element ref="StorageDefinition" minOccurs="0" maxOccurs="unbounded" />
                        </xs:sequence>
                        <xs:attribute name="Id" type="xs:string" />
                        <xs:attribute name="Type" type="xs:string" />
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="Features" minOccurs="0" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="Feature" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element ref="StorageDefinitionRef" minOccurs="0" maxOccurs="unbounded" />
                    <xs:element ref="StorageDefinition" minOccurs="0" maxOccurs="unbounded" />
                    <xs:element ref="Array" minOccurs="0" maxOccurs="unbounded" />
                  </xs:sequence>
                  <xs:attribute name="Id" type="xs:string" />
                  <xs:attribute name="Name" type="xs:string" />
                  <xs:attribute name="Maximum" type="xs:string" />
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="FeatureGroups" minOccurs="0" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="FeatureGroup" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element ref="FeatureGroupRef" minOccurs="0" maxOccurs="unbounded" />
                    <xs:element ref="FeatureRef" minOccurs="0" maxOccurs="unbounded" />
                  </xs:sequence>
                  <xs:attribute name="Id" type="xs:string" />
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="Levels" minOccurs="0" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="Default" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element ref="FeatureGroupRef" minOccurs="0" maxOccurs="unbounded" />
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="Level" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element ref="FeatureRef" minOccurs="0" maxOccurs="unbounded" />
                    <xs:element ref="FeatureGroupRef" minOccurs="0" maxOccurs="unbounded" />
                  </xs:sequence>
                  <xs:attribute name="Name" type="xs:string" />
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute name="Maximum" type="xs:string" />
            <xs:attribute name="Minimum" type="xs:string" />
          </xs:complexType>
        </xs:element>
      </xs:sequence>
      <xs:attribute name="Version" type="xs:string" />
    </xs:complexType>
  </xs:element>
  <xs:element name="NewDataSet" msdata:IsDataSet="true" msdata:UseCurrentLocale="true">
    <xs:complexType>
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element ref="StorageDefinition" />
        <xs:element ref="StorageDefinitionRef" />
        <xs:element ref="Array" />
        <xs:element ref="FeatureGroupRef" />
        <xs:element ref="FeatureRef" />
        <xs:element ref="GameProfile" />
      </xs:choice>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== jessaskey/mhedit/GameEditor.Core/Xsd/GameProfile.xml
<?xml version="1.0" encoding="utf-8" ?> 
<!-- This is a working example of a Major Havoc Profile -->
<GameProfile xmlns="http://askey.org/GameProfile"
             xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
             xsi:schemaLocation="http://askey.org/GameProfile GameProfile.xsd"
             Version="1.0.0.0">
    <GameInfo>
        <Name>Major Havoc</Name>
        <Version>1.0</Version>
        <Manufacturer>Atari Inc.</Manufacturer>
        <ReleaseDate>1984-01</ReleaseDate>
        <Comment>Production ROMs</Comment>
    </GameInfo>
    <MemoryMap Id="AlphaProcessor"
               AddressWidth="16"
               AddressBase="0x0000"
               BusWidth="8">
        <ROM Id="PagedProgramRom"
             Address="0x2000"
             Size="0x2000">
            <Memory>
                <Bank Id="Bank_1Q">
                    <EPROM Id="EPROM_1Q"
                            Name="136025.215"
                            Size="16384"
                            Width="8"/>
                </Bank>
                <Bank Id="Bank_1NP">
                    <EPROM Id="EPROM_1NP"
                            Name="136025.216"
                            Size="16384"
                            Width="8"/>
                </Bank>
            </Memory>
            <Pages>
                <Page Id="PagedProgramRom.Page_0">
                    <BankRef Id="Bank_1Q" />
                </Page>
                <Page Id="PagedProgramRom.Page_1">
                    <BankRef Id="Bank_1Q" />
                </Page>
                <Page Id="PagedProgramRom.Page_2">
                    <BankRef Id="Bank_1NP" />
                </Page>
                <Page Id="PagedProgramRom.Page_3">
                    <BankRef Id="Bank_1NP" />
                </Page>
            </Pages>
        </ROM>
        <ROM Id="ProgramRom"
             Address="0x8000"
             Size="0x8000">
            <Memory>
                <Bank Id="Bank_1MN">
                    <EPROM Id="EPROM_1MN"
                            Name="136025.217"
                            Size="16384"
                            Width="8"/>
                </Bank>
                <Bank Id="Bank_1L">
                    <EPROM Id="EPROM_1L"
                            Name="136025.318"
                            Size="16384"
                            Width="8"/>
                </Bank>
            </Memory>
            <Pages>
                <Page Id="ProgramRom.Page_0">
                    <BankRef Id="Bank_1MN" />
                    <BankRef Id="Bank_1L" />
                </Page>
            </Pages>
        </ROM>
    </MemoryMap>
    <ProgramMemory>
        <TextSegment>
            <Data Id="AlphaProcessor.ProgramRom.Page_0"
                  Reserved="no"
                  Start="0x2000"
                  Length="0x0234"/>
            <Checksum Id="Checksum1L"
                      Type="Crc32">
                <EPROMRef Id="EPROM_1L"
                          Start="0x0000"
                          End="0xFFFF"/>
                <StorageDefinition Id="Checksum_1L">
                    <Array Type="short">
                        <PageRef Id="PagedProgramRom.Page_0">
                            0x1111
                        </PageRef>
                    </Array>
                </StorageDefinition>
            </Checksum>
        </TextSegment>
    </ProgramMemory>
    <!-- Individual Maze Features,
    The Maximum value represents total # allowed for all mazes combined. -->
    <Features>
        <Feature Id="MazeHint"
                 Maximum="12">
            <!--Not every level has a hint. -->
            <StorageDefinition>
                <Array Id="HintIndex"
                       Type="byte"
                       Storage="value"
                       Size="12">
                    <PageRef Id="ProgramRom.Page_0">
                        0x93FE
                    </PageRef>
                </Array>
                <Array Id="PointerToHintString"
                       Type="string"
                       Storage="pointer"
                       Size="12">
                    <PageRef Id="ProgramRom.Page_0">
                        0xE48b
                    </PageRef>
                </Array>
            </StorageDefinition>
        </Feature>
        <Feature Id="ReactoidTime"
                 Maximum="16">
            <!-- Every level MUST have a Reactoid timer value. -->
            <StorageDefinition >
                <Array Id="ReactoidMeltdownTimes"
                       Type="byte"
                       Storage="value"
                       Size="16">
                    <PageRef Id="PagedProgramRom.Page_1">
                        0x3355
                    </PageRef>
                </Array>
            </StorageDefinition>
        </Feature>
        <Feature Id="Reactoid"
                 Maximum="16">
            <!-- Every level MUST have a Reactoid. It's actually stored as
            the first maze object in the MazeEnemiesObjectList List.-->
            <StorageDefinition Id="MazeEnemiesList">
                <Array Id="MazeEnemiesList"
                       Type="object"
                       Storage="pointer"
                       Size="16">
                    <PageRef Id="PagedProgramRom.Page_0">
                        0x2581
                    </PageRef>
                </Array>
            </StorageDefinition>
        </Feature> 
        <Feature Id="Pyroid">
            <!-- Only one Reactoid ever, so no delimiter before the Pyroids. -->
            <StorageDefinitionRef Id="MazeEnemiesList"
                                  Order="1"/>
        </Feature>
        <Feature Id="Perkoid">
            <!-- May be many Pyroids in list already so use delimiter before
            inserting the Perkoids. -->
            <StorageDefinitionRef Id="MazeEnemiesList"
                                  Order="2">
                <Delimiter>
                    FE
                </Delimiter>
            </StorageDefinitionRef>
        </Feature>      
        <Feature Id="Oxoid">
            <StorageDefinition >
                <Array Id="OxoidList"
                       Type="object"
                       Storage="pointer"
                       Size="16">
                    <PageRef Id="PagedProgramRom.Page_1">
                        0x25A9
                    </PageRef>
                </Array>
            </StorageDefinition>
        </Feature>
        <Feature Id="Lightning">
            <StorageDefinition >
                <Array Id="LightningList"
                       Type="object"
                       Storage="pointer"
                       Size="16">
                    <PageRef Id="PagedProgramRom.Page_1">
                        0x25D1
                    </PageRef>
                </Array>
            </StorageDefinition>
        </Feature>
        <Feature Id="Arrow">
            <StorageDefinition >
                <Array Id="ArrowList"
                       Type="object"
                       Storage="pointer"
                       Size="16">
                    <PageRef Id="PagedProgramRom.Page_1">
                        0x25F9
                    </PageRef>
                </Array>
            </StorageDefinition>
        </Feature>
        <Feature Id="MazeWall">
            <StorageDefinition >
                <Array Id="MazeWallList"
                       Type="object"
                       Storage="pointer"
                       Size="16">
                    <PageRef Id="PagedProgramRom.Page_1">
                        0x2647
                    </PageRef>
                </Array>
            </StorageDefinition>
        </Feature>
        <Feature Id="OneWaySign">
            <StorageDefinition >
                <Array Id="OneWaySignList"
                       Type="object"
                       Storage="pointer"
                       Size="16">
                    <PageRef Id="PagedProgramRom.Page_1">
                        0x2677
                    </PageRef>
                </Array>
            </StorageDefinition>
        </Feature>
        <Feature Id="LockAndKey">
            <StorageDefinition >
                <Array Id="LockAndKeyList"
                       Type="object"
                       Storage="pointer"
                       Size="16">
                    <PageRef Id="PagedProgramRom.Page_1">
                        0x26D1
                    </PageRef>
                </Array>
            </StorageDefinition>
        </Feature>
        <Feature Id="Stalactite">
            <StorageDefinition >
                <Array Id="StalactiteList"
                       Type="object"
                       Storage="pointer"
                       Size="16">
                    <PageRef Id="PagedProgramRom.Page_1">
                        0x26B3
                    </PageRef>
                </Array>
            </StorageDefinition>
        </Feature>
        <Feature Id="EscapePod"
                 Maximum="4">
            <!-- Only Maze type 1 Supports Escape Pods. -->
            <StorageDefinition >
                <Array Id="EscapePodEnabled"
                       Type="boolean"
                       Storage="value"
                       Size="4">
                    <PageRef Id="PagedProgramRom.Page_1">
                        0x32FF
                    </PageRef>
                </Array>
            </StorageDefinition>
        </Feature>
        <Feature Id="Clock"
                 Maximum="16">
            <StorageDefinition >
                <Array Id="ClockEnabled"
                       Type="boolean"
                       Storage="value"
                       Size="16">
